version: '3'
services:
  sonarr:
    container_name: sonarr
    image: 'linuxserver/sonarr:latest'
    restart: unless-stopped
    ports:
      - '8989:8989'
    environment:
      - 'PUID=${UID}'
      - 'PGID=${GID}'
      - 'TZ=${TZ}'
    volumes:
      - '/etc/localtime:/etc/localtime:ro'
      - '${DATA}/sonarr:/config'
      - '${MEDIA}/Serije:/tv'
      - '${MEDIA}/Downloads:/downloads'
  radarr:
    container_name: radarr
    image: 'linuxserver/radarr:latest'
    restart: unless-stopped
    ports:
      - '7878:7878'
    environment:
      - 'PUID=${UID}'
      - 'PGID=${GID}'
      - 'TZ=${TZ}'
    volumes:
      - '/etc/localtime:/etc/localtime:ro'
      - '${DATA}/radarr:/config'
      - '${MEDIA}/Filmovi:/movies'
      - '${MEDIA}/Downloads:/downloads'
  lidarr:
    container_name: lidarr
    image: lscr.io/linuxserver/lidarr:latest
    restart: unless-stopped
    ports:
      - "8686:8686" # Lidarr web UI
    environment:
      - 'PUID=${UID}'
      - 'PGID=${GID}'
      - 'TZ=${TZ}'
    volumes:
      - '${DATA}/lidarr:/config'
      - '${MEDIA}/Downloads/lidarr:/downloads'
      - '${MEDIA}/Music:/music'
      - '${MEDIA}/AudioBooks:/audiobooks'
  bazarr:
    image: lscr.io/linuxserver/bazarr:latest
    container_name: bazarr
    environment:
      - 'PUID=${UID}'
      - 'PGID=${GID}'
      - 'TZ=${TZ}'
    volumes:
      - '${DATA}/bazarr/config:/config'
      - '${MEDIA}/Filmovi:/movies' #optional
      - '${MEDIA}/Serije:/tv' #optional
    ports:
      - 6767:6767
    restart: unless-stopped
  jackett:
    container_name: jackett
    image: 'linuxserver/jackett:latest'
    restart: unless-stopped
    ports:
      - '9117:9117'
    environment:
      - 'PUID=${UID}'
      - 'PGID=${GID}'
      - 'TZ=${TZ}'
    volumes:
      - '/etc/localtime:/etc/localtime:ro'
      - '${DATA}/jackett:/config'
  heimdall:
    image: 'lscr.io/linuxserver/heimdall:latest'
    container_name: heimdall
    environment:
      - 'PUID=${UID}'
      - 'PGID=${GID}'
      - 'TZ=${TZ}'
    volumes:
      - '${DATA}/heimdall:/config'
    ports:
      - '8080:80'
      - '8443:443'
    restart: unless-stopped
  transmission:
    container_name: transmission
    image: 'lscr.io/linuxserver/transmission:latest'
    environment:
      - 'PUID=${UID}'
      - 'PGID=${GID}'
      - 'TZ=${TZ}'
    volumes:
      - '${DATA}/transmission:/config'
      - '${MEDIA}/Downloads:/downloads'
      - '${MEDIA}/Downloads/transmission-watch:/watch'
      - '${MEDIA}/AudioBooks:/audiobooks'
      - '${MEDIA}/Serije:/tvshows'
      - '${MEDIA}/Filmovi:/movies'
    ports:
      - '9091:9091'
      - '51413:51413'
      - '51313:51413/udp'
    restart: unless-stopped
  jellyfin:
    image: 'linuxserver/jellyfin:latest'
    container_name: jellyfin
    environment:
      - 'PUID=${UID}'
      - 'PGID=${GID}'
      - 'TZ=${TZ}'
      - DOCKER_MODS=linuxserver/mods:jellyfin-opencl-intel
    ports:
      - '8096:8096'
    volumes:
      - '${DATA}/jellyfin/config:/config'
      - '${DATA}/jellyfin/cache:/cache'
      - '${MEDIA}/Filmovi:/data/movies'
      - '${MEDIA}/Serije:/data/tvshows'
      - '${MEDIA}/Music:/data/music'
      - '${MEDIA}/Crtici:/data/kids'
      - '${MEDIA}/Misc:/data/misc'
      - '${MEDIA}/MusicVideos:/data/music-videos'
    devices:
      - /dev/dri/renderD128:/dev/dri/renderD128
      - /dev/dri/card0:/dev/dri/card0
    restart: unless-stopped
  navidrome:
    image: deluan/navidrome:latest
    container_name: navidrome 
    user: 1000:1000
    ports:
      - '4533:4533'
    restart: unless-stopped
    environment:
      ND_SCANSCHEDULE: 1h
      ND_LOGLEVEL: info  
      ND_SESSIONTIMEOUT: 24h
      ND_BASEURL: ''
      ND_ENABLETRANSCODINGCONFIG: "true"
      ND_TRANSCODINGCACHESIZE: "200MB"
      ND_DEFAULTTHEME: "Spotify-ish"
      ND_LASTFM_ENABLED: "true"
      ND_LASTFM_APIKEY: "${ND_LASTFM_APIKEY}"
      ND_LASTFM_SECRET: "${ND_LASTFM_SECRET}"
      ND_LASTFM_LANGUAGE: "en"
    volumes:
      - '${DATA}/navidrome:/data'
      - '${MEDIA}/Music:/music:ro'
  beets:
   image: lscr.io/linuxserver/beets:latest
   container_name: beets
   environment:
     - 'PUID=${UID}'
     - 'PGID=${GID}'
     - 'TZ=${TZ}'
   volumes:
     - '${DATA}/beets:/config'
     - '${MEDIA}/Music:/music'
     - '${MEDIA}/Downloads:/downloads'
   ports:
     - 8337:8337
   restart: unless-stopped
  swag:
    image: lscr.io/linuxserver/swag:latest
    container_name: swag
    cap_add:
      - NET_ADMIN
    environment:
      - 'PUID=${UID}'
      - 'PGID=${GID}'
      - 'TZ=${TZ}'
      - 'URL=${URL}'
      - 'SUBDOMAINS=${SUBDOMAINS}'
      - 'EXTRA_DOMAINS=${EXTRA_DOMAINS}'
      - 'EMAIL=${EMAIL}'
      - 'VALIDATION=${VALIDATION}'
    volumes:
      - '${DATA}/swag:/config'
    ports:
      - 443:443
      - 80:80
    restart: unless-stopped
  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "8081:80/tcp"
      - "8444:443/tcp"
    environment:
      - 'TZ=${TZ}'
      - 'WEBPASSWORD=${PIHOLE_WEBPASSWORD}'
      - 'SERVERIP=${PIHOLE_HOST_SERVERIP}'
      - 'FTLCONF_LOCAL_IPV4=${PIHOLE_HOST_SERVERIP}'
    volumes:
       - '${DATA}/pihole/etc-pihole/:/etc/pihole/'
       - '${DATA}/pihole/etc-dnsmasq.d/:/etc/dnsmasq.d/'
    dns:
      - 127.0.0.1
      - 1.1.1.1
    restart: unless-stopped
      # unbound:
      #   container_name: unbound
      #   image: mvance/unbound:latest
      #   volumes:
      #     - '${DATA}/unbound:/opt/unbound/etc/unbound'
      #   ports:
      #     - "5335:53/tcp"
      #     - "5335:53/udp"
      #   healthcheck:
      #     disable: true
      #   restart: unless-stopped
  audiobookshelf:
    container_name: audiobookshelf
    image: ghcr.io/advplyr/audiobookshelf:latest
    environment:
      - 'AUDIOBOOKSHELF_UID=${UID}'
      - 'AUDIOBOOKSHELF_GID=${GID}'
    ports:
      - 13378:80
    volumes:
      - '${MEDIA}/AudioBooks:/audiobooks'
      - '${MEDIA}/Podcasts:/podcasts'
      - '${DATA}/audiobookshelf:/config'
      - '${DATA}/audiobookshelf/metadata:/metadata'

