version: '3'
services:
  sonarr:
    container_name: sonarr
    image: 'linuxserver/sonarr:latest'
    restart: unless-stopped
    ports:
      - '8989:8989'
    environment:
      - 'PUID=${UID}'
      - 'PGID=${GID}'
      - 'TZ=${TZ}'
    volumes:
      - '/etc/localtime:/etc/localtime:ro'
      - '${DATA}/sonarr:/config'
      - '${MEDIA}/Serije:/tv'
      - '${MEDIA}/Downloads:/downloads'
  radarr:
    container_name: radarr
    image: 'linuxserver/radarr:latest'
    restart: unless-stopped
    ports:
      - '7878:7878'
    environment:
      - 'PUID=${UID}'
      - 'PGID=${GID}'
      - 'TZ=${TZ}'
    volumes:
      - '/etc/localtime:/etc/localtime:ro'
      - '${DATA}/radarr:/config'
      - '${MEDIA}/Filmovi:/movies'
      - '${MEDIA}/Downloads:/downloads'
  jackett:
    container_name: jackett
    image: 'linuxserver/jackett:latest'
    restart: unless-stopped
    ports:
      - '9117:9117'
    environment:
      - 'PUID=${UID}'
      - 'PGID=${GID}'
      - 'TZ=${TZ}'
    volumes:
      - '/etc/localtime:/etc/localtime:ro'
      - '${DATA}/jackett:/config'
  heimdall:
    image: 'lscr.io/linuxserver/heimdall:latest'
    container_name: heimdall
    environment:
      - 'PUID=${UID}'
      - 'PGID=${GID}'
      - 'TZ=${TZ}'
    volumes:
      - '${DATA}/heimdall:/config'
    ports:
      - '8081:80'
      - '8443:443'
    restart: unless-stopped
  transmission:
    container_name: transmission
    image: 'lscr.io/linuxserver/transmission:latest'
    environment:
      - 'PUID=${UID}'
      - 'PGID=${GID}'
      - 'TZ=${TZ}'
    volumes:
      - '${DATA}/transmission:/config'
      - '${MEDIA}/Downloads:/downloads'
      - '${MEDIA}/Downloads/transmission-watch:/watch'
    ports:
      - '9091:9091'
      - '51413:51413'
      - '51313:51413/udp'
    restart: unless-stopped
  yacht:
    container_name: yacht
    image: selfhostedpro/yacht
    restart: unless-stopped
    ports:
      - '8000:8000'
    volumes:
      - '${DATA}/yacht:/config'
      - '/var/run/docker.sock:/var/run/docker.sock'
  jellyfin:
    image: 'linuxserver/jellyfin:latest'
    container_name: jellyfin
    environment:
      - 'PUID=${UID}'
      - 'PGID=${GID}'
      - 'TZ=${TZ}'
    ports:
      - '8096:8096'
    volumes:
      - '${DATA}/jellyfin/config:/config'
      - '${DATA}/jellyfin/cache:/cache'
      - '${MEDIA}/Filmovi:/data/movies'
      - '${MEDIA}/Serije:/data/tvshows'
    restart: unless-stopped
