
# Loads default set of integrations. Do not remove.
default_config:

# Load frontend themes from the themes folder
frontend:
  themes: !include_dir_merge_named themes

automation: !include automations.yaml
automation alarm: !include alarm.yaml
script: !include scripts.yaml
scene: !include scenes.yaml
template: !include template.yaml

http:
  use_x_forwarded_for: true
  trusted_proxies:
    - 172.18.0.0/16
    - 127.0.0.1

input_number:
  alarm_siren_volume:
    name: Alarm Siren Volume
    icon: mdi:volume-high
    min: 0
    max: 1
    step: 0.05
  alarm_beep_volume:
    name: Alarm Entry Beep Volume
    icon: mdi:volume-medium
    min: 0
    max: 1
    step: 0.05

alarm_control_panel: !include alarm_panel.yaml
